import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

// Register the PWA Service Worker (generated by vite-plugin-pwa)
// This enables: "Add to Home Screen" prompt + offline caching
import { registerSW } from 'virtual:pwa-register'

registerSW({
  onNeedRefresh() {
    // A new version is available — auto-update silently
  },
  onOfflineReady() {
    console.log('Kids Hero is ready to work offline! 🎮')
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
